#!/usr/bin/env bash

# Environment setup
set -o pipefail

function print_usage() {
    cat <<EOF
Usage: elgato <command> <ip_address_list> [--help]

Elgato light management for Bash

Command list:
  on                 Turn the light(s) on
  off                Turn the light(s) off
  toggle             Turn the light(s) on or off

Example:
$ elgato on 172.30.1.181 172.30.1.143

Dependencies:
  curl               The Client for URLs CLI tool
  jq                 The JSON Query CLI tool

Required arguments:
  command            The light command, see above
  ip_address_list    A space separated list of light IP addresses

Optional arguments:
  -h, --help         Show this help message and exit
EOF
}

if [[ $# -lt 2 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    print_usage
    exit 1
fi

# Dependency check
for cmd in curl jq; do
    if ! command -v "${cmd}" >/dev/null; then
        log_error "ERROR: Missing dependency - '${cmd}'"
        exit 1
    fi
done

# -----------------------------------------------------------------------------
#  Argument assignment
# -----------------------------------------------------------------------------

declare light_command="${1}"
shift

declare -a light_ips
for arg in "$@"; do
    light_ips+=("${arg}")
done

declare -a valid_commands=("on" "off" "toggle")
if [[ ! "${valid_commands[*]}" =~ ${light_command} ]]; then
    echo "The command '${light_command}' is not valid."
    exit 1
fi

declare url_suffix=":9123/elgato/lights"
declare state=""
declare MAX_CONCURRENT_JOBS=10
declare current_jobs=0

# -----------------------------------------------------------------------------
#  Colour and log definitions
# -----------------------------------------------------------------------------

export RED=$'\033[31m'
export BGRED=$'\033[41m'
export GREEN=$'\033[32m'
export MAGENTA=$'\033[35m'
export CYAN=$'\033[36m'
export BLUE=$'\033[34m'
export YELLOW=$'\033[33m'
export WHITE=$'\033[37m'
export NORMAL=$'\033[00m'
export BOLD=$'\033[01m'
export CLEARLINE=$'\033[K'

function log_line() {
    # Usage: log_line <character> <length>
    # Defaults character: '-' length: 80
    local length=80
    local char="-"
    if [[ -n $1 ]]; then
        char="$1"
    fi
    if [[ -n $2 ]]; then
        length="$2"
    fi
    printf "${BOLD}${MAGENTA}${char}%.0s${NORMAL}" $(seq 1 "${length}") >&2
    echo
}

function log_title() {
    printf "\n${BOLD}${GREEN}%s${NORMAL}\n" "$@" >&2
    log_line "="
}

function log_header() {
    printf "\n${GREEN}${GREEN}%s${NORMAL}\n" "$@" >&2
    local title="$*"
    local length=${#title}
    log_line "-" "${length}"
}

function log_message() {
    printf "${NORMAL}%s${NORMAL}\n" "$@" >&2
}

function log_warning() {
    printf "${YELLOW}%s${NORMAL}\n" "$@" >&2
}

function log_error() {
    printf "${RED}%s${NORMAL}\n" "$@" >&2
}

function log_success() {
    printf "${GREEN}✔${NORMAL} %b\n" "${@}"
}

function log_failure() {
    printf "${RED}✖${NORMAL} %b\n" "${@}"
}

# -----------------------------------------------------------------------------
#  Body Functions
# -----------------------------------------------------------------------------
function get_state() {
    local light_ip="${1}"
    if state_data="$(curl -s -m 4 -X GET -H "Content-Type: application/json" "http://${light_ip}${url_suffix}")"; then
        state="$(echo "${state_data}" | jq -r '.lights[0].on')"
        return
    fi
    log_failure "Failure: ${light_ip}"
}

function api_put_call() {
    local light_ip="${1}"
    local on_state="${2}"
    local payload='{"numberOfLights":1,"lights":[{"on":'"${on_state}"'}]}'

    if curl -s -m 4 -X PUT -H "Content-Type: application/json" -d "${payload}" "http://${light_ip}${url_suffix}" >/dev/null 2>&1; then
        log_success "Success: ${light_ip}"
    else
        log_failure "Failure: ${light_ip}"
    fi
}

function turn_on() {
    api_put_call "${1}" 1 &
}

function turn_off() {
    api_put_call "${1}" 0 &
}

function toggle_on_off() {
    local light_ip="${1}"
    get_state "${light_ip}"
    if [[ "${state}" -eq 1 ]]; then
        turn_off "${light_ip}" &
    else
        turn_on "${light_ip}" &
    fi
}

# -----------------------------------------------------------------------------
#  Body Logic
# -----------------------------------------------------------------------------
log_title " Elgato Light Management"
log_message "  Command: ${light_command}"
for light_ip in "${light_ips[@]}"; do
    log_message " Light IP: ${light_ip}"
done

function process_lights() {
    local action=$1
    log_header " Power ${2}"
    for light_ip in "${light_ips[@]}"; do
        "${action}" "${light_ip}" &
        ((current_jobs++))
        if ((current_jobs >= MAX_CONCURRENT_JOBS)); then
            wait
            current_jobs=0
        fi
    done
}

case "${light_command}" in
    "toggle")
        process_lights toggle_on_off "Toggle"
        ;;
    "on")
        process_lights turn_on "On"
        ;;
    "off")
        process_lights turn_off "Off"
        ;;
    *)
        log_error "Invalid command"
        print_usage
        exit 1
        ;;
esac

wait
